# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
