# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0003_remove_school_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics', verbose_name='Profile Picture')),
                ('wechat', models.CharField(blank=True, max_length=128, unique=True, verbose_name='WeChat')),
                ('qq', models.IntegerField(blank=True, unique=True, verbose_name='QQ')),
                ('mobile', models.CharField(blank=True, max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
