# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='City/'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(blank=True, max_length=128, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='firstname',
            field=models.CharField(blank=True, max_length=128, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='lastname',
            field=models.CharField(blank=True, max_length=128, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='province',
            field=models.CharField(blank=True, max_length=128, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Profile Picture'),
        ),
    ]
