# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20171203_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='City'),
        ),
    ]
