# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20171203_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('runtime', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
                ('imgurl', models.URLField(verbose_name='Image URL')),
                ('downloadurl', models.CharField(max_length=256, verbose_name='Download URL')),
                ('votes', models.IntegerField()),
                ('rate', models.FloatField(max_length=4)),
                ('desc', models.CharField(max_length=256, verbose_name='Description')),
                ('dateadded', models.DateField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('genres', models.ManyToManyField(related_name='genres', to='basic_app.Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='School',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
